#!/bin/sh

IFACE="$1"
STATE="$2"

logger -t wireguard-dispatcher "IFACE=$IFACE STATE=$STATE"
echo "$(date) IFACE=$1 STATE=$2" >> /tmp/nm-dispatch.log

if [ "$IFACE" = "wwan0" ] && [ "$STATE" = "up" ]; then
    if ! nmcli -t -f GENERAL.STATE device show wg0 2>/dev/null | grep -q "100"; then
        logger -t wireguard-dispatcher "Starting wg0 in 20s"
        sleep 20
        nmcli connection up wg0
    fi
fi