require conf/distro/poky.conf

DISTRO = "drone-os"
DISTRO_NAME = "DroneOS"
DISTRO_VERSION = "1.2"

# Bootloader
PREFERRED_PROVIDER_virtual/bootloader = "u-boot"
PREFERRED_PROVIDER_u-boot = "u-boot"
RPI_USE_U_BOOT = "1"

# Init system
INIT_MANAGER = "systemd"
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = ""
DISTRO_FEATURES:append = " systemd usrmerge rauc"
DISTRO_FEATURES:remove = "sysvinit"

# Modem
PACKAGECONFIG:append:pn-networkmanager = " modemmanager"
PACKAGECONFIG:append:pn-modemmanager = " qmi mbim"

# Kernel
CMDLINE:append = " audit=0"

# Partition layout
WKS_FILE = "drone-image.wks.in"
IMAGE_FSTYPES:append = " ext4 wic wic.bz2 wic.bmap"