header:
  version: 14

machine: raspberrypi5

repos:
  poky:
    url: https://git.yoctoproject.org/poky
    branch: scarthgap
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    url: https://github.com/openembedded/meta-openembedded
    branch: scarthgap
    layers:
      meta-oe:
      meta-python:
      meta-networking:

  meta-raspberrypi:
    url: https://github.com/agherzan/meta-raspberrypi
    branch: scarthgap

  meta-ros:
    url: https://github.com/ros/meta-ros
    branch: scarthgap
    layers:
      meta-ros-common:
      meta-ros2:
      meta-ros2-jazzy:

  meta-drone:
    path: layers/meta-drone

target:
  - drone-image

local_conf_header:
  common: |
    DISTRO = "drone-os"
    PACKAGE_CLASSES = "package_ipk"
    ENABLE_UART = "1"
    RPI_EXTRA_CONFIG = "dtoverlay=uart2"
    LICENSE_FLAGS_ACCEPTED:append = " synaptics-killswitch"
    INHERIT:remove = "create-spdx"
