#@TYPE: Machine
#@NAME: Drone CM5
#@DESCRIPTION: Drone CM5 on Kelvin carrier board

KMACHINE = "raspberrypi-cm5-io-board"
require conf/machine/raspberrypi-cm5-io-board.conf


# UARTs Kelvin carrier board
RPI_EXTRA_CONFIG = '\n\
# Kelvin carrier board\n\
dtoverlay=uart0-pi5\n\
dtoverlay=uart2-pi5\n\
dtoverlay=uart4-pi5\n\
\n\
# CAN - MCP2515 on SPI1 CS0 (GPIO18), INT GPIO25\n\
dtparam=spi=on\n\
dtoverlay=spi1-1cs\n\
dtoverlay=mcp2515,spi1-0,oscillator=8000000,interrupt=25\n\
\n\
# Dual IMX219\n\
start_x=1\n\
gpu_mem=256\n\
dtoverlay=imx219,cam0\n\
dtoverlay=imx219,cam1\n\
'

KERNEL_MODULE_AUTOLOAD += "can can-raw mcp251x"