#@TYPE: Machine
#@NAME: Drone RPi5
#@DESCRIPTION: Drone RPi5 development board

require conf/machine/raspberrypi5.conf

# UART2 for Flight Controller (ttyAMA2)
RPI_EXTRA_CONFIG = '\n\
# Drone RPi5\n\
dtoverlay=uart2-pi5\n\
'