header:
  version: 14

local_conf_header:
  development: |
    EXTRA_IMAGE_FEATURES += "debug-tweaks"

    IMAGE_INSTALL:append = " \
        gdb \
        strace \
        tcpdump \
        vim \
        btop \
    "
