#!/bin/sh

IFACE="$1"
STATE="$2"

if [ "$IFACE" = "wwan0" ] && [ "$STATE" = "up" ]; then
    logger -t wireguard-dispatcher "wwan0 is up, starting WireGuard"

    sleep 5

    nmcli connection up wg0
fi