# =============================================================================
# meta-raspi-drone/conf/layer.conf
# =============================================================================

BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "raspi-drone"
BBFILE_PATTERN_raspi-drone  = "^${LAYERDIR}/"
BBFILE_PRIORITY_raspi-drone = "10"

# Declare dependencies on other layers
LAYERDEPENDS_raspi-drone = "core openembedded-layer raspberrypi"

# Compatible Yocto release series
LAYERSERIES_COMPAT_raspi-drone = "scarthgap"
